class Id3:
    PER_FRAME_MAX_SIZE = '16M'
    TOTAL_MAX_SIZE = '256M'

    VALUE_SEPARATOR = 0x00

    NUMBER_OF_DECLARED_FRAME_TYPES = 83

    TEXTUAL_FRAME_LATIN_1_ENCODING = '$00'
    TEXTUAL_FRAME_USC_2_ENCODING = '$01'
    TEXTUAL_FRAME_UTF_16_ENCODING = '$02'
    TEXTUAL_FRAME_UTF_8_ENCODING = '$03'

    TEXTUAL_FRAME_ENCODING = 00
